from tkinter import * 
from tkinter.ttk import *
from PIL import Image, ImageTk
from gui.drawing import CircuitDrawing
from engine import *

class MainWindow:
    def __init__(self) -> None:
        root = Tk()
        icon = ImageTk.PhotoImage(Image.open(r"icon.png"))
        root.iconphoto(True, icon)
        root.title("Patoc: a graphical tool for quantum circuits")
        root.config(bg="white")

        # org1 = Gate(0,"in", pos=(0,0))
        # org2 = Gate(1,"in", pos=(0,1))
        # org3 = Gate(2,"in", pos=(0,2))
        # org4 = Gate(3,"in", pos=(0,3))
        # h1 = Gate(4,"H", pos=(1,0))
        # cx1 = Gate(5,"CNOT", pos=(1,1))
        # h2 = Gate(6,"H", pos=(2,1))
        # h3 = Gate(7,"H", pos=(2,2))
        # cx2 = Gate(8,"CNOT", pos=(3,0))
        # h4 = Gate(9,"H", pos=(4,1))
        # d1 = Gate(10,"D", pos=(5,1))
        # h5 = Gate(11,"H", pos=(7,1))
        # cx3 = Gate(12,"CNOT", pos=(7,2))
        # g1 = Gate(13,"G", pos=(8,0))
        # g2 = Gate(14,"G", pos=(9,0))
        # dst1 = Gate(15,"out", pos=(10,0))
        # dst2 = Gate(16,"out", pos=(10,1))
        # dst3 = Gate(17,"out", pos=(10,2))
        # circuit = Circuit("cz-one-cnot", [org1,org2,org3,org4,h1,cx1,h2,h3,cx2,h4,d1,h5,cx3,g1,g2,dst1,dst2,dst3],[0,1,2,3],[15,16,17])
        # circuit.connect(0, 4, wiring=(0,0))
        # circuit.connect(1, 5, wiring=(0,0))
        # circuit.connect(2, 5, wiring=(0,1))
        # circuit.connect(3, 17, wiring=(0,0))
        # circuit.connect(4, 8, wiring=(0,0))
        # circuit.connect(5, 6, wiring=(0,0))
        # circuit.connect(5, 7, wiring=(1,0))
        # circuit.connect(6, 8, wiring=(0,1))
        # circuit.connect(7, 12, wiring=(0,1))
        # circuit.connect(8, 13, wiring=(0,0))
        # circuit.connect(8, 9, wiring=(1,0))
        # circuit.connect(9, 10, wiring=(0,0))
        # circuit.connect(10, 11, wiring=(0,0))
        # circuit.connect(10, 12, wiring=(1,0))
        # circuit.connect(11, 13, wiring=(0,1))
        # circuit.connect(12, 14, wiring=(0,1))
        # circuit.connect(12, 16, wiring=(1,0))
        # circuit.connect(13, 14, wiring=(0,0))
        # circuit.connect(14, 15, wiring=(0,0))

        # org1 = Gate(0,"in", pos=(0,0))
        # org2 = Gate(1,"in", pos=(0,1))
        # org3 = Gate(2,"in", pos=(0,2))
        # h1 = Gate(3,"H", pos=(1,0))
        # h2 = Gate(4,"H", pos=(1,1))
        # h3 = Gate(5,"H", pos=(3,1))
        # h4 = Gate(6,"H", pos=(4,0))
        # dst1 = Gate(7,"out", pos=(5,0))
        # dst2 = Gate(8,"out", pos=(5,1))
        # dst3 = Gate(9,"out", pos=(5,2))
        # circuit = Circuit("cz-one-cnot", [org1,org2,org3,h1,h2,h3,h4,dst1,dst2,dst3],[0,1,2],[7,8,9])
        # circuit.connect(0, 3, wiring=(0,0))
        # circuit.connect(1, 4, wiring=(0,0))
        # circuit.connect(2, 9, wiring=(0,0))
        # circuit.connect(3, 5, wiring=(0,0))
        # circuit.connect(6, 7, wiring=(0,0))
        # circuit.connect(4, 6, wiring=(0,0))
        # circuit.connect(5, 8, wiring=(0,0))

        in0 = Gate(0,"in", pos=(0,0))
        in1 = Gate(0,"in", pos=(0,1))
        in2 = Gate(0,"in", pos=(0,2))
        in3 = Gate(0,"in", pos=(0,2))
        in4 = Gate(0,"in", pos=(0,2))
        in5 = Gate(0,"in", pos=(0,2))
        a = Gate(0,"A", pos=(1,0))
        b = Gate(0,"B", pos=(1,1))
        c = Gate(0,"C", pos=(2,0))
        e = Gate(0,"E", arity=3, pos=(3,0))
        cx = Gate(0,"CNOT", pos=(4,0))
        f = Gate(0,"F", pos=(4,2))
        h = Gate(0,"H", arity=4, pos=(0,2))
        j = Gate(0,"J", arity=3, pos=(1,[2,4,5]))
        k = Gate(0,"K", arity=3, pos=(3,[2,3,5]))
        out0 = Gate(0,"out", pos=(5,0))
        out1 = Gate(0,"out", pos=(5,1))
        out2 = Gate(0,"out", pos=(5,2))
        out3 = Gate(0,"out", pos=(5,0))
        out4 = Gate(0,"out", pos=(5,1))
        out5 = Gate(0,"out", pos=(5,2))
        gates = [in0,in1,in2,in3,in4,in5,a,b,c,e,cx,f,h,j,k,out0,out1,out2,out3,out4,out5]
        for i in range(len(gates)):
            gates[i].id = i

        circuit = Circuit("cz-one-cnot", gates, [0,1,2,3,4,5])
        circuit.connect(in0, a, wiring=(0,0))
        circuit.connect(a, c, wiring=(0,0))
        circuit.connect(c, e, wiring=(0,0))
        circuit.connect(e, cx, wiring=(0,0))
        circuit.connect(cx, out0, wiring=(0,0))
        circuit.connect(in1, b, wiring=(0,0))
        circuit.connect(b, e, wiring=(0,1))
        circuit.connect(e, cx, wiring=(1,1))
        circuit.connect(cx, out1, wiring=(1,0))
        circuit.connect(in2, h, wiring=(0,0))
        circuit.connect(h, j, wiring=(0,0))
        circuit.connect(j, e, wiring=(0,2))
        circuit.connect(e, k, wiring=(2,0))
        circuit.connect(k, f, wiring=(0,0))
        circuit.connect(f, out2, wiring=(0,0))
        circuit.connect(in3, h, wiring=(0,1))
        circuit.connect(h, k, wiring=(1,1))
        circuit.connect(k, out3, wiring=(1,0))
        circuit.connect(in4, h, wiring=(0,2))
        circuit.connect(h, j, wiring=(2,1))
        circuit.connect(j, out4, wiring=(1,0))
        circuit.connect(in5, h, wiring=(0,3))
        circuit.connect(h, j, wiring=(3,2))
        circuit.connect(j, k, wiring=(2,2))
        circuit.connect(k, out5, wiring=(2,0))


        canvas = Canvas(root, height=400, width=650, bg="white", highlightthickness=0)
        canvas.pack()
        config = {}
        self.drawing = CircuitDrawing(canvas, circuit, config)

        root.eval('tk::PlaceWindow . center')
        root.mainloop()

def printtest():
    print("This is a print from /app/window.py")